baseURL = ''
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false
enableInlineShortcodes = true
removePathAccents = true
title = 'BourkConf'
theme = 'pego'


[languages]
  [languages.fr]
    languageCode = "fr"
    languageName = "Français"
    weight = 1
    title = "BourkConf"
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 2
    title = "BourkConf"
